#!/usr/bin/env python3
"""Generate a standalone soil variability analysis HTML dashboard for a grower.

Usage:
    export DATA_PIPELINE_DATA_ROOT=/path/to/runtime
    python src/dashboard.py --grower-slug il-northern-grower --output output/dashboard.html
"""

import argparse
import os
import sys
from pathlib import Path

import plotly.io as pio

# Ensure this script can import sibling modules when run directly
sys.path.insert(0, str(Path(__file__).parent))

from data_loader import load_grower_data
from figures import (
    compute_kpis,
    fig_drainage_class_distribution,
    fig_field_variability_radar,
    fig_geospatial_soil_health,
    fig_monthly_precipitation,
    fig_ndvi_by_year_crop,
    fig_ph_cec_om_correlation,
    fig_soil_health_score_chart,
    fig_soil_ph_distribution,
    fig_temperature_envelope,
)

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>Soil Variability Analysis Dashboard — {grower}</title>
<script src="https://cdn.plot.ly/plotly-2.35.2.min.js"></script>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    background: #e8f5e9; color: #2c3e50; padding: 20px;
  }}
  .container {{ max-width: 1400px; margin: 0 auto; }}
  h1 {{ font-size: 28px; margin-bottom: 4px; }}
  .subtitle {{ color: #7f8c8d; font-size: 14px; margin-bottom: 24px; }}
  .section {{ background: #fff; border-radius: 10px; padding: 20px; margin-bottom: 20px;
              box-shadow: 0 1px 4px rgba(0,0,0,0.08); }}
  .section-title {{ font-size: 18px; font-weight: 600; margin-bottom: 16px;
                     padding-bottom: 8px; border-bottom: 2px solid #3498db; }}
  .grid-2 {{ display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }}
  .grid-full {{ grid-column: 1 / -1; }}
  @media (max-width: 900px) {{ .grid-2 {{ grid-template-columns: 1fr; }} }}
  .kpi-row {{ display: flex; flex-wrap: wrap; gap: 12px; }}
  .kpi-card {{
    flex: 1; min-width: 160px; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    border-radius: 10px; padding: 18px 16px; color: #fff; text-align: center;
  }}
  .kpi-card .value {{ font-size: 28px; font-weight: 700; }}
  .kpi-card .label {{ font-size: 12px; opacity: 0.85; margin-top: 4px; }}
  .footer {{ text-align: center; color: #95a5a6; font-size: 12px; margin-top: 24px; }}
</style>
</head>
<body>
<div class="container">
<h1>Soil Variability Analysis Dashboard</h1>
<p class="subtitle">{grower} · {field_count} fields</p>

<div class="section">
  <div class="section-title">KPI Summary</div>
  {kpi_html}
</div>

<div class="section">
  <div class="section-title">Exploratory Visualizations</div>
  <div class="grid-2">
    <div>{fig_ph_dist}</div>
    <div>{fig_ndvi_year}</div>
    <div class="grid-full">{fig_corr}</div>
  </div>
</div>

<div class="section">
  <div class="section-title">Geospatial Analysis</div>
  {fig_map}
</div>

<div class="section">
  <div class="section-title">Weather & Climate Analysis</div>
  <div class="grid-2">
    <div>{fig_precip}</div>
    <div>{fig_temp}</div>
  </div>
</div>

<div class="section">
  <div class="section-title">Soil Health & Sustainability</div>
  <div class="grid-2">
    <div>{fig_soil_score}</div>
    <div>{fig_drainage}</div>
    <div class="grid-full">{fig_radar}</div>
  </div>
</div>

<div class="section">
  <div class="section-title">Decision Support Summary</div>
  <div class="grid-full" style="padding: 8px 0; line-height: 1.7;">
    <p>
      Fields with well-drained soils and higher organic matter consistently show
      stronger NDVI and soil health scores. Low-pH fields and those with poor
      drainage are priority candidates for variable-rate lime application and
      tile drainage investment. OM %, CEC, drainage class, and pH are the
      strongest predictors of soil health; NDVI provides a seasonal check on
      whether soil constraints are actually limiting crop performance. Monitor
      low-scoring fields across seasons to confirm whether remediation efforts
      are closing the yield gap.
    </p>
  </div>
</div>

<div class="footer">
  Generated by Soil Variability Dashboard · Data: {grower} (My Farm Advisor)
</div>
</div>
</body>
</html>"""


def build_kpi_html(kpis: dict) -> str:
    cards = [
        ("Fields", str(kpis["n_fields"])),
        ("Total Acres", f'{kpis["total_acres"]:,.1f}'),
        ("Avg NDVI", str(kpis["avg_ndvi"]) if kpis["avg_ndvi"] else "N/A"),
        ("Rainfall (mm/yr)", str(kpis["avg_annual_rainfall_mm"])),
        ("Soil Health", f'{kpis["avg_soil_health"]:.1f}/100'),
        ("Erosion Risk", kpis["dominant_erosion_risk"].title()),
    ]
    colors = [
        "linear-gradient(135deg, #667eea, #764ba2)",
        "linear-gradient(135deg, #f093fb, #f5576c)",
        "linear-gradient(135deg, #4facfe, #00f2fe)",
        "linear-gradient(135deg, #43e97b, #38f9d7)",
        "linear-gradient(135deg, #fa709a, #fee140)",
        "linear-gradient(135deg, #a18cd1, #fbc2eb)",
    ]
    parts = []
    for (label, value), bg in zip(cards, colors):
        parts.append(
            f'<div class="kpi-card" style="background: {bg};">'
            f'<div class="value">{value}</div>'
            f'<div class="label">{label}</div></div>'
        )
    return '<div class="kpi-row">' + "".join(parts) + "</div>"


def _resolve_grower_dir(grower_slug: str) -> Path:
    data_root = os.environ.get("DATA_PIPELINE_DATA_ROOT")
    if not data_root:
        raise OSError(
            "DATA_PIPELINE_DATA_ROOT must be set. "
            "Example: export DATA_PIPELINE_DATA_ROOT=/home/coder/my-farm-advisor-runtime"
        )
    return Path(data_root) / "data-pipeline" / "growers" / grower_slug


def generate(grower_slug: str, output_path: str):
    grower_dir = _resolve_grower_dir(grower_slug)
    data = load_grower_data(grower_dir)
    kpis = compute_kpis(data)
    data["_kpis"] = kpis

    kpi_html = build_kpi_html(kpis)

    fig_ph_dist = pio.to_html(
        fig_soil_ph_distribution(data), full_html=False, include_plotlyjs=False
    )
    fig_ndvi_year = pio.to_html(
        fig_ndvi_by_year_crop(data), full_html=False, include_plotlyjs=False
    )
    fig_corr = pio.to_html(
        fig_ph_cec_om_correlation(data), full_html=False, include_plotlyjs=False
    )
    fig_map = pio.to_html(
        fig_geospatial_soil_health(data), full_html=False, include_plotlyjs=False
    )
    fig_precip = pio.to_html(
        fig_monthly_precipitation(data), full_html=False, include_plotlyjs=False
    )
    fig_temp = pio.to_html(
        fig_temperature_envelope(data), full_html=False, include_plotlyjs=False
    )
    fig_soil_score = pio.to_html(
        fig_soil_health_score_chart(data), full_html=False, include_plotlyjs=False
    )
    fig_drainage = pio.to_html(
        fig_drainage_class_distribution(data), full_html=False, include_plotlyjs=False
    )
    fig_radar = pio.to_html(
        fig_field_variability_radar(data), full_html=False, include_plotlyjs=False
    )

    n_fields = kpis.get("n_fields", 0)

    html = HTML_TEMPLATE.format(
        grower=grower_slug,
        field_count=n_fields,
        kpi_html=kpi_html,
        fig_ph_dist=fig_ph_dist,
        fig_ndvi_year=fig_ndvi_year,
        fig_corr=fig_corr,
        fig_map=fig_map,
        fig_precip=fig_precip,
        fig_temp=fig_temp,
        fig_soil_score=fig_soil_score,
        fig_drainage=fig_drainage,
        fig_radar=fig_radar,
    )

    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(html)
    print(f"Dashboard written to {out.resolve()}")


def main():
    parser = argparse.ArgumentParser(
        description="Generate Soil Variability Analysis Dashboard for a grower"
    )
    parser.add_argument(
        "--grower-slug", required=True,
        help="Grower slug (e.g. il-northern-grower)",
    )
    parser.add_argument(
        "--output",
        default="output/soil_variability_dashboard.html",
        help="Output HTML file path",
    )
    args = parser.parse_args()
    generate(args.grower_slug, args.output)


if __name__ == "__main__":
    main()
